// combine this with util if this turns out to be small?
module.exports = {
  BLACK_COLOR: 0,
  WHITE_COLOR: 255,
  BLACK_COLOR_THRES: 40,
  WHITE_COLOR_THRES: 245,
  MIN_BLOCK_SIZE: 8,
  MAX_BLOCK_SIZE: 40000,
  BLOCK_MIN_WHITE_PIX_COUNT: 625,
  BLOCK_MIN_BLACK_PIX_COUNT: 4,
  Y_COORDS: [1, -1, 0, 0],
  X_COORDS: [0, 0, 1, -1],
  GAP_VAL: -1,
  SUBBUBBLE_BOUNDARY: 15,
  WORD_BREAK_MIN_LEN: 30,
  DISSECT_RATIO_THRES: 0.6,
  MERGE_RATIO_THRES: 0.85
};